module.exports = [
  '',
  'about-me',
  'agenda',
  'the-game',
  'the-stack',
  'caniuse-webgpu',
  'irenderer',
  'loose-coupling',
  'canvas2d-for-mvp',
  'adding-a-webgl-impl',
  'moving-to-webgpu',
  'webgpu-differences',
  'demo-time',
  'learning-resources',
  'thank-you',
];
